/*
 * WebGPU AVBD backend: runs the paper-faithful AVBD primal/dual iteration
 * loop on the GPU. Broadphase, narrowphase, and warmstarting stay on the CPU
 * (Solver::prepareStep); the per-iteration work — graph-colored per-body 6x6
 * primal solves and per-constraint dual updates — runs fully GPU-resident
 * with a single readback at the end of the step.
 */

#pragma once

#include "solver.h"

struct WebGpuDevice;

std::unique_ptr<PhysicsBackend> makeWebGpuAvbdPhysicsBackend(WebGpuDevice *device);

// Lightweight per-process stats from the most recent WebGPU AVBD step, for
// server metrics/benchmark reporting.
struct AvbdGpuSolverStats
{
    bool active;            // a WebGPU AVBD backend has stepped
    float gpuIterateMs;     // GPU upload + iterate + readback time, last step
    float buildFrameMs;     // CPU flatten/adjacency/coloring time, last step
    float buildBodiesMs;    // buildFrame: body gather + parallel fill
    float buildRecordsMs;   // buildFrame: manifold/joint/spring record walk
    float buildSlotsMs;     // buildFrame: sphere slot retire/acquire + pair records
    float buildAdjMs;       // buildFrame: CSR adjacency count/prefix/fill
    float buildColorMs;     // buildFrame: greedy coloring + color ranges
    float submitMs;         // buffer writes + command encoding + submit, last step
    float waitMs;           // synchronous readback map waits, last step
    float applyMs;          // CPU apply of positions/dual state, last step
    int bodies;             // solved (dynamic, constrained) bodies
    int contacts;           // total contact records (CPU manifolds + GPU sphere pairs)
    int spherePairs;        // sphere-sphere contacts generated by the GPU narrowphase
    int joints;
    int springs;
    int colors;             // graph colors used by the primal solve
    int cpuIterateFallbacks; // steps that fell back to the CPU iteration loop
};

const AvbdGpuSolverStats &avbdGpuSolverStats();
