/*
 * Copyright (c) 2026 Chris Giles
 *
 * Permission to use, copy, modify, distribute and sell this software
 * and its documentation for any purpose is hereby granted without fee,
 * provided that the above copyright notice appear in all copies.
 * Chris Giles makes no representations about the suitability
 * of this software for any purpose.
 * It is provided "as is" without express or implied warranty.
 */

#pragma once

#include "solver.h"
#include "render_backend.h"

#if AVBD_ENABLE_WEBGPU && AVBD_HAS_DAWN
#include <dawn/webgpu_cpp.h>
#endif

struct SDL_Window;

struct WebGpuPreviewCamera
{
    float3 eye;
    float3 target;
    float3 up;
    float fovYDeg;
};

struct WebGpuRenderOptions
{
    bool showGroundGrid = true;
    bool showShapeEdges = true;
    float3 lightDirection = {0.45f, 0.80f, 0.55f};
    float3 backgroundColor = {0.035f, 0.055f, 0.085f};
};

struct WebGpuTimingStats
{
    float lastMs;
    float avgMs;
    float recentAvgMs;
    float minMs;
    float maxMs;
    int samples;
    int recentSamples;
    int recentIndex;
    float recentSumMs;
    float recentMs[64];
};

struct WebGpuContext
{
    bool initialized;
    bool deviceReady;
    bool smokeTestPassed;
    char status[1024];
    char smokeStatus[1024];
    char computeStatus[1024];
    char presentStatus[1024];
    char predictionStatus[1024];
    char velocityStatus[1024];
    char boundsStatus[1024];
    char mortonStatus[1024];
    char mortonSortStatus[1024];
    char pairStatus[1024];
    char sapStatus[1024];
    char jointTopologyStatus[1024];
    char runtimeStatus[1024];
    float previewComputeMs;
    float previewRenderMs;
    float previewTotalMs;
    int previewBatchCount;
    int previewInstanceCount;
    int previewBoxInstances;
    int previewSphereInstances;
    int previewCapsuleInstances;
    int previewCylinderInstances;
    int previewMeshAssetInstances;
    float predictionMs;
    float predictionMaxError;
    float predictionMaxAngularError;
    int predictionSamples;
    float velocityMs;
    float velocityMaxLinearError;
    float velocityMaxAngularError;
    int velocitySamples;
    float boundsMs;
    float boundsMaxError;
    int boundsSamples;
    float mortonMs;
    int mortonMismatches;
    int mortonSamples;
    float mortonSortMs;
    int mortonSortMismatches;
    int mortonSortCount;
    float pairMs;
    int pairCandidates;
    int pairSphereHits;
    int pairAllPairsSphereHits;
    int pairMissedSphereHits;
    int pairMismatches;
    float sapMs;
    int sapCandidates;
    int sapSphereHits;
    int sapAllPairsSphereHits;
    int sapMissedSphereHits;
    int sapMismatches;
    int sapBestAxis;
    int sapAxisCandidates[3];
    int sapAxisSphereHits[3];
    int sapAxisMissedSphereHits[3];
    int sapCounterReadbackBytes;
    float sapCounterReadbackMs;
    int sapPairReadbackBytes;
    float sapPairReadbackMs;
    float jointTopologyMs;
    int jointTopologyJoints;
    int jointTopologyBodyRefs;
    int jointTopologyActiveBodies;
    int jointTopologyMaxPerBody;
    int jointTopologyMismatches;
    int jointTopologyReadbackBytes;
    int jointColorCount;
    int jointColorConflicts;
    int jointColorMinBucket;
    int jointColorMaxBucket;
    int jointColorReadbackBytes;
    float jointResidualMax;
    float jointResidualRms;
    int jointResidualReadbackBytes;
    float jointProposalMaxCorrection;
    float jointProposalRmsCorrection;
    int jointProposalActiveBodies;
    int jointProposalMaxPerBody;
    int jointProposalReadbackBytes;
    int jointProposalIterations;
    float jointProposalResidualAfterMax;
    float jointProposalResidualAfterRms;
    int jointProposalResidualReadbackBytes;
    int jointProposalFinalPositionReady;
    int jointProposalFinalPositionBodyCount;
    int jointProposalFinalPositionBytes;
    int jointProposalFinalPositionAbsolute;
    int jointProposalSeededFromContact;
    int jointProposalAppliedPositionBodies;
    int jointProposalAppliedPositionReadbackBytes;
    float jointProposalAppliedPositionMaxDelta;
    float jointProposalAppliedPositionChecksum;
    float jointProposalAppliedPositionMs;
    int jointProposalFinalPositionAsyncReadbackPending;
    int jointProposalFinalPositionAsyncReadbackScheduled;
    int jointProposalFinalPositionAsyncReadbackConsumed;
    int jointProposalFinalPositionAsyncReadbackDropped;
    float jointProposalFinalPositionAsyncReadbackWaitMs;
    int jointProposalFinalPositionAsyncReadbackBodyCount;
    int jointProposalFinalPositionAsyncReadbackBytes;
    int jointProposalFinalPositionAsyncReadbackAbsolute;
    int sphereContactCount;
    int sphereContactExternalContacts;
    int sphereContactExternalGroundContacts;
    int sphereContactReadbackBytes;
    float sphereContactMs;
    float sphereContactReadbackMs;
    int sphereContactBodyRefs;
    int sphereContactActiveBodies;
    int sphereContactMaxPerBody;
    float sphereContactAvgPerActiveBody;
    int sphereContactAdjacencyReadbackBytes;
    int sphereContactAdjacencyListBytes;
    int sphereContactAdjacencyCapacity;
    int sphereContactAdjacencyWrittenRefs;
    int sphereContactAdjacencyOverflowRefs;
    float sphereContactAdjacencyMs;
    int sphereContactGatherRefs;
    int sphereContactGatherActiveBodies;
    int sphereContactGatherMaxPerBody;
    int sphereContactGatherMismatches;
    int sphereContactGatherReadbackBytes;
    float sphereContactGatherNormalChecksum;
    int sphereContactProposalActiveBodies;
    float sphereContactProposalMaxCorrection;
    float sphereContactProposalCorrectionChecksum;
    float sphereContactGatherMs;
    int sphereContactProposalOutputActiveBodies;
    int sphereContactProposalOutputReadbackBytes;
    float sphereContactProposalOutputMaxDelta;
    float sphereContactProposalOutputChecksum;
    float sphereContactProposalOutputMs;
    int sphereContactProposalResidualReadbackBytes;
    float sphereContactProposalResidualBeforeMax;
    float sphereContactProposalResidualAfterMax;
    float sphereContactProposalResidualBeforeChecksum;
    float sphereContactProposalResidualAfterChecksum;
    float sphereContactProposalResidualMs;
    int sphereContactIterationCount;
    float sphereContactIterationMs;
    float sphereContactIterationRelaxation;
    float sphereContactIterationResidualAfterMax;
    float sphereContactIterationResidualAfterChecksum;
    int sphereContactFinalPositionReady;
    int sphereContactFinalPositionBodyCount;
    int sphereContactFinalPositionBytes;
    int sphereContactFinalPositionSource;
    std::vector<float3> sphereContactFinalReferencePositions;
    int sphereContactAppliedPositionBodies;
    int sphereContactAppliedPositionReadbackBytes;
    float sphereContactAppliedPositionMaxDelta;
    float sphereContactAppliedPositionChecksum;
    float sphereContactAppliedPositionMs;
    float sphereContactAppliedPositionWaitMs;
    float sphereContactAppliedPositionCpuMs;
    int sphereContactFinalPositionReadbackDeferred;
    int sphereContactFinalPositionAsyncReadbackPending;
    int sphereContactFinalPositionAsyncReadbackScheduled;
    int sphereContactFinalPositionAsyncReadbackConsumed;
    int sphereContactFinalPositionAsyncReadbackDropped;
    float sphereContactFinalPositionAsyncReadbackWaitMs;
    int sphereContactFinalPositionAsyncReadbackBodyCount;
    int sphereContactFinalPositionAsyncReadbackBytes;
    int sphereContactFinalPositionAsyncReadbackSource;
    std::vector<float3> sphereContactAsyncReferencePositions;
    int sphereGroundReceiverCount;
    int sphereGroundDynamicSphereCount;
    int sphereGroundCandidateCount;
    int directSphereCylinderBodyCount;
    int directSphereCylinderCandidateCount;
    int directSphereCapsuleBodyCount;
    int directSphereCapsuleCandidateCount;
    int directSphereBoxBodyCount;
    int directSphereBoxCandidateCount;
    int directBoxBodyCount;
    int directBoxPairCandidateCount;
    int directRoundBodyCount;
    int directRoundPairCandidateCount;
    int directGpuContactRecordCount;
    int directGpuRoundPairCandidateCount;
    int directGpuBoxPairCandidateCount;
    int directGpuCounterReadbackBytes;
    float directGpuCounterReadbackMs;
    int directSphereContactAppliedPositionBodies;
    int directGroundAppliedPositionBodies;
    int predictionAppliedBodies;
    int predictionAppliedReadbackBytes;
    float predictionAppliedMs;
    int velocityAppliedBodies;
    int velocityAppliedReadbackBytes;
    float velocityAppliedMs;
    float sphereGroundTop;
    float sphereGroundMs;
    float runtimeTotalMs;
    float runtimeSyncMs;
    float runtimePredictionMs;
    float runtimeVelocityMs;
    float runtimeCpuFallbackMs;
    float runtimeMaxLinearError;
    float runtimeMaxAngularError;
    int runtimeFrames;
    int runtimeFallbacks;
    WebGpuTimingStats predictionTiming;
    WebGpuTimingStats velocityTiming;
    WebGpuTimingStats boundsTiming;
    WebGpuTimingStats mortonTiming;
    WebGpuTimingStats mortonSortTiming;
    WebGpuTimingStats pairTiming;
    WebGpuTimingStats sapTiming;

    WebGpuContext();
    bool initializeDeviceOnly();
    bool initialize(SDL_Window *window);
    bool runOffscreenSmokeTest(int width, int height);
    bool runComputeSmokeTest();
    bool runBodyPredictionDiagnostic(const SimWorld &world, float dt, float gravity, bool validateReadback = true);
    bool applyBodyPredictionOutputs(Solver &solver);
    bool runVelocityUpdateDiagnostic(const SimWorld &world, float dt, bool validateReadback = true);
    bool applyVelocityOutputs(Solver &solver);
    bool runBoundsDiagnostic(const SimWorld &world);
    bool runMortonDiagnostic(const SimWorld &world);
    bool runMortonSortDiagnostic(const SimWorld &world);
    bool runBroadphasePairDiagnostic(const SimWorld &world);
    bool runSweepAndPruneDiagnostic(const SimWorld &world);
    bool runJointTopologyDiagnostic(const SimWorld &world, int proposalIterations = 1, bool diagnosticReadback = true, bool seedFromContactFinalPositions = false);
    bool runSweepAndPrunePairs(const SimWorld &world, std::vector<BroadphasePair> &pairs, std::vector<ExternalManifoldContact> *sphereContacts = 0, bool counterOnly = false, bool validateResidentContacts = true, bool suppressSphereSpherePairs = false, bool suppressSphereGroundPairs = false, bool emitSphereGroundContacts = false, bool runResidentContactSolve = true, bool suppressNonSpherePairOutput = false, bool directSpherePositionSolve = false, int residentContactIterations = 4, float residentContactRelaxation = 0.10f, bool forceResidentCounterlessContacts = false);
    bool runSphereSphereContacts(const SimWorld &world, const std::vector<BroadphasePair> &pairs, std::vector<ExternalManifoldContact> &contacts);
    bool runSphereGroundCorrection(const SimWorld &world, bool includeSpheres = true);
    void resetDiagnosticTimingStats();
    bool clearSurface(int width, int height);
    bool clearWindowSurface(SDL_Window *window, int width, int height);
    bool renderTriangleSurface(int width, int height);
    bool renderInstancedPreviewSurface(const SimWorld &world, const WebGpuPreviewCamera &camera, int width, int height);
    bool renderInstancedPreviewSurface(const SimWorld &world, const WebGpuPreviewCamera &camera, const WebGpuRenderOptions &options, int width, int height);
    void shutdown();
    const char *statusText() const;
    const char *smokeStatusText() const;
    const char *computeStatusText() const;
    const char *presentStatusText() const;
    const char *predictionStatusText() const;
    const char *velocityStatusText() const;
    const char *boundsStatusText() const;
    const char *mortonStatusText() const;
    const char *mortonSortStatusText() const;
    const char *pairStatusText() const;
    const char *sapStatusText() const;
    const char *jointTopologyStatusText() const;
    const char *runtimeStatusText() const;
    float previewComputeMillis() const;
    float previewRenderMillis() const;
    float previewTotalMillis() const;
    int previewBatchCountValue() const;
    int previewInstanceCountValue() const;
    int previewBoxInstanceCount() const;
    int previewSphereInstanceCount() const;
    int previewCapsuleInstanceCount() const;
    int previewCylinderInstanceCount() const;
    int previewMeshAssetInstanceCount() const;
    float predictionMillis() const;
    float predictionMaxErrorValue() const;
    float predictionMaxAngularErrorValue() const;
    int predictionSampleCount() const;
    float velocityMillis() const;
    float velocityMaxLinearErrorValue() const;
    float velocityMaxAngularErrorValue() const;
    int velocitySampleCount() const;
    float boundsMillis() const;
    float boundsMaxErrorValue() const;
    int boundsSampleCount() const;
    float mortonMillis() const;
    int mortonMismatchCount() const;
    int mortonSampleCount() const;
    float mortonSortMillis() const;
    int mortonSortMismatchCount() const;
    int mortonSortItemCount() const;
    float pairMillis() const;
    int pairCandidateCount() const;
    int pairSphereHitCount() const;
    int pairAllPairsSphereHitCount() const;
    int pairMissedSphereHitCount() const;
    int pairMismatchCount() const;
    float sapMillis() const;
    int sapCandidateCount() const;
    int sapSphereHitCount() const;
    int sapAllPairsSphereHitCount() const;
    int sapMissedSphereHitCount() const;
    int sapMismatchCount() const;
    int sapCounterReadbackByteCount() const;
    float sapCounterReadbackMillis() const;
    int sapPairReadbackByteCount() const;
    float sapPairReadbackMillis() const;
    float jointTopologyMillis() const;
    int jointTopologyJointCount() const;
    int jointTopologyBodyRefCount() const;
    int jointTopologyActiveBodyCount() const;
    int jointTopologyMaxPerBodyCount() const;
    int jointTopologyMismatchCount() const;
    int jointTopologyReadbackByteCount() const;
    int jointColorCountValue() const;
    int jointColorConflictCount() const;
    int jointColorMinBucketCount() const;
    int jointColorMaxBucketCount() const;
    int jointColorReadbackByteCount() const;
    float jointResidualMaxValue() const;
    float jointResidualRmsValue() const;
    int jointResidualReadbackByteCount() const;
    float jointProposalMaxCorrectionValue() const;
    float jointProposalRmsCorrectionValue() const;
    int jointProposalActiveBodyCount() const;
    int jointProposalMaxPerBodyCount() const;
    int jointProposalReadbackByteCount() const;
    int jointProposalIterationCount() const;
    float jointProposalResidualAfterMaxValue() const;
    float jointProposalResidualAfterRmsValue() const;
    int jointProposalResidualReadbackByteCount() const;
    int jointProposalFinalPositionReadyValue() const;
    int jointProposalFinalPositionBodyCountValue() const;
    int jointProposalFinalPositionByteCount() const;
    int jointProposalFinalPositionAbsoluteValue() const;
    int jointProposalSeededFromContactValue() const;
    bool applyJointProposalFinalPositions(Solver &solver);
    bool scheduleJointProposalFinalPositionReadback();
    bool consumePendingJointProposalFinalPositions(Solver &solver);
    int jointProposalAppliedPositionBodyCount() const;
    int jointProposalAppliedPositionReadbackByteCount() const;
    float jointProposalAppliedPositionMaxDeltaValue() const;
    float jointProposalAppliedPositionChecksumValue() const;
    float jointProposalAppliedPositionMillis() const;
    int jointProposalFinalPositionAsyncReadbackPendingValue() const;
    int jointProposalFinalPositionAsyncReadbackScheduledValue() const;
    int jointProposalFinalPositionAsyncReadbackConsumedValue() const;
    int jointProposalFinalPositionAsyncReadbackDroppedValue() const;
    float jointProposalFinalPositionAsyncReadbackWaitMillis() const;
    int jointProposalFinalPositionAsyncReadbackBodyCountValue() const;
    int jointProposalFinalPositionAsyncReadbackByteCount() const;
    int jointProposalFinalPositionAsyncReadbackAbsoluteValue() const;
    int sphereContactCountValue() const;
    int sphereContactExternalContactCount() const;
    int sphereContactExternalGroundContactCount() const;
    int sphereContactReadbackByteCount() const;
    float sphereContactMillis() const;
    float sphereContactReadbackMillis() const;
    int sphereContactBodyRefCount() const;
    int sphereContactActiveBodyCount() const;
    int sphereContactMaxPerBodyCount() const;
    float sphereContactAvgPerActiveBodyValue() const;
    int sphereContactAdjacencyReadbackByteCount() const;
    int sphereContactAdjacencyBufferByteCount() const;
    int sphereContactAdjacencyCapacityValue() const;
    int sphereContactAdjacencyWrittenRefCount() const;
    int sphereContactAdjacencyOverflowRefCount() const;
    float sphereContactAdjacencyMillis() const;
    int sphereContactGatherRefCount() const;
    int sphereContactGatherActiveBodyCount() const;
    int sphereContactGatherMaxPerBodyCount() const;
    int sphereContactGatherMismatchCount() const;
    int sphereContactGatherReadbackByteCount() const;
    float sphereContactGatherNormalChecksumValue() const;
    int sphereContactProposalActiveBodyCount() const;
    float sphereContactProposalMaxCorrectionValue() const;
    float sphereContactProposalCorrectionChecksumValue() const;
    float sphereContactGatherMillis() const;
    int sphereContactProposalOutputActiveBodyCount() const;
    int sphereContactProposalOutputReadbackByteCount() const;
    float sphereContactProposalOutputMaxDeltaValue() const;
    float sphereContactProposalOutputChecksumValue() const;
    float sphereContactProposalOutputMillis() const;
    int sphereContactProposalResidualReadbackByteCount() const;
    float sphereContactProposalResidualBeforeMaxValue() const;
    float sphereContactProposalResidualAfterMaxValue() const;
    float sphereContactProposalResidualBeforeChecksumValue() const;
    float sphereContactProposalResidualAfterChecksumValue() const;
    float sphereContactProposalResidualMillis() const;
    int sphereContactIterationCountValue() const;
    float sphereContactIterationMillis() const;
    float sphereContactIterationRelaxationValue() const;
    float sphereContactIterationResidualAfterMaxValue() const;
    float sphereContactIterationResidualAfterChecksumValue() const;
    int sphereContactFinalPositionReadyValue() const;
    int sphereContactFinalPositionBodyCountValue() const;
    int sphereContactFinalPositionByteCount() const;
    const char *sphereContactFinalPositionSourceText() const;
    bool applySphereContactFinalPositions(Solver &solver);
    int sphereContactAppliedPositionBodyCount() const;
    int sphereContactAppliedPositionReadbackByteCount() const;
    float sphereContactAppliedPositionMaxDeltaValue() const;
    float sphereContactAppliedPositionChecksumValue() const;
    float sphereContactAppliedPositionMillis() const;
    float sphereContactAppliedPositionWaitMillis() const;
    float sphereContactAppliedPositionCpuMillis() const;
    int sphereContactFinalPositionReadbackDeferredValue() const;
    bool scheduleSphereContactFinalPositionReadback();
    bool consumePendingSphereContactFinalPositions(Solver &solver);
    int sphereContactFinalPositionAsyncReadbackPendingValue() const;
    int sphereContactFinalPositionAsyncReadbackScheduledValue() const;
    int sphereContactFinalPositionAsyncReadbackConsumedValue() const;
    int sphereContactFinalPositionAsyncReadbackDroppedValue() const;
    float sphereContactFinalPositionAsyncReadbackWaitMillis() const;
    int sphereContactFinalPositionAsyncReadbackBodyCountValue() const;
    int sphereContactFinalPositionAsyncReadbackByteCount() const;
    const char *sphereContactFinalPositionAsyncReadbackSourceText() const;
    int sphereGroundReceiverCountValue() const;
    int sphereGroundDynamicSphereCountValue() const;
    int sphereGroundCandidateCountValue() const;
    int directSphereCylinderBodyCountValue() const;
    int directSphereCylinderCandidateCountValue() const;
    int directSphereCapsuleBodyCountValue() const;
    int directSphereCapsuleCandidateCountValue() const;
    int directSphereBoxBodyCountValue() const;
    int directSphereBoxCandidateCountValue() const;
    int directBoxBodyCountValue() const;
    int directBoxPairCandidateCountValue() const;
    int directRoundBodyCountValue() const;
    int directRoundPairCandidateCountValue() const;
    int directGpuContactRecordCountValue() const;
    int directGpuRoundPairCandidateCountValue() const;
    int directGpuBoxPairCandidateCountValue() const;
    int directGpuCounterReadbackByteCount() const;
    float directGpuCounterReadbackMillis() const;
    int directSphereContactAppliedPositionBodyCount() const;
    int directGroundAppliedPositionBodyCount() const;
    int predictionAppliedBodyCount() const;
    int predictionAppliedReadbackByteCount() const;
    float predictionAppliedMillis() const;
    int velocityAppliedBodyCount() const;
    int velocityAppliedReadbackByteCount() const;
    float velocityAppliedMillis() const;
    float sphereGroundTopValue() const;
    float sphereGroundMillis() const;
    float runtimeTotalMillis() const;
    float runtimeSyncMillis() const;
    float runtimePredictionMillis() const;
    float runtimeVelocityMillis() const;
    float runtimeCpuFallbackMillis() const;
    float runtimeMaxLinearErrorValue() const;
    float runtimeMaxAngularErrorValue() const;
    int runtimeFrameCount() const;
    int runtimeFallbackCount() const;

#if AVBD_ENABLE_WEBGPU && AVBD_HAS_DAWN
    wgpu::Instance instance;
    wgpu::Surface surface;
    wgpu::Adapter adapter;
    wgpu::Device device;
    wgpu::Queue queue;
    wgpu::Buffer bodyInputBuffer;
    uint64_t bodyInputBufferBytes;
    wgpu::Buffer bodyInstanceBuffer;
    uint64_t bodyInstanceBufferBytes;
    wgpu::Buffer bodyPreviewCameraBuffer;
    wgpu::Texture bodyPreviewDepthTexture;
    wgpu::TextureView bodyPreviewDepthView;
    wgpu::Buffer predictionInputBuffer;
    uint64_t predictionInputBufferBytes;
    wgpu::Buffer predictionOutputBuffer;
    uint64_t predictionOutputBufferBytes;
    wgpu::Buffer predictionReadbackBuffer;
    uint64_t predictionReadbackBufferBytes;
    wgpu::Buffer predictionParamsBuffer;
    wgpu::BindGroupLayout predictionBindGroupLayout;
    wgpu::ComputePipeline predictionPipeline;
    wgpu::Buffer velocityInputBuffer;
    uint64_t velocityInputBufferBytes;
    wgpu::Buffer velocityOutputBuffer;
    uint64_t velocityOutputBufferBytes;
    wgpu::Buffer velocityReadbackBuffer;
    uint64_t velocityReadbackBufferBytes;
    wgpu::Buffer velocityParamsBuffer;
    wgpu::BindGroupLayout velocityBindGroupLayout;
    wgpu::ComputePipeline velocityPipeline;
    wgpu::Buffer boundsInputBuffer;
    uint64_t boundsInputBufferBytes;
    wgpu::Buffer boundsOutputBuffer;
    uint64_t boundsOutputBufferBytes;
    wgpu::Buffer boundsReadbackBuffer;
    uint64_t boundsReadbackBufferBytes;
    wgpu::Buffer boundsParamsBuffer;
    wgpu::BindGroupLayout boundsBindGroupLayout;
    wgpu::ComputePipeline boundsPipeline;
    wgpu::Buffer mortonInputBuffer;
    uint64_t mortonInputBufferBytes;
    wgpu::Buffer mortonOutputBuffer;
    uint64_t mortonOutputBufferBytes;
    wgpu::Buffer mortonReadbackBuffer;
    uint64_t mortonReadbackBufferBytes;
    wgpu::Buffer mortonParamsBuffer;
    wgpu::BindGroupLayout mortonBindGroupLayout;
    wgpu::ComputePipeline mortonPipeline;
    wgpu::Buffer mortonSortBuffer;
    uint64_t mortonSortBufferBytes;
    wgpu::Buffer mortonSortReadbackBuffer;
    uint64_t mortonSortReadbackBufferBytes;
    wgpu::Buffer mortonSortParamsBuffer;
    wgpu::BindGroupLayout mortonSortBindGroupLayout;
    wgpu::ComputePipeline mortonSortPipeline;
    wgpu::Buffer pairBodyBuffer;
    uint64_t pairBodyBufferBytes;
    wgpu::Buffer pairItemBuffer;
    uint64_t pairItemBufferBytes;
    wgpu::Buffer pairCountersBuffer;
    uint64_t pairCountersBufferBytes;
    wgpu::Buffer pairReadbackBuffer;
    uint64_t pairReadbackBufferBytes;
    wgpu::Buffer pairParamsBuffer;
    wgpu::BindGroupLayout pairBindGroupLayout;
    wgpu::ComputePipeline pairPipeline;
    wgpu::Buffer sapIntervalBuffer;
    uint64_t sapIntervalBufferBytes;
    wgpu::Buffer sapCountersBuffer;
    uint64_t sapCountersBufferBytes;
    wgpu::Buffer sapReadbackBuffer;
    uint64_t sapReadbackBufferBytes;
    wgpu::Buffer sapPairOutputBuffer;
    uint64_t sapPairOutputBufferBytes;
    wgpu::Buffer sapPairReadbackBuffer;
    uint64_t sapPairReadbackBufferBytes;
    wgpu::Buffer sapDirectSphereParamsBuffer;
    wgpu::Buffer jointTopologyInputBuffer;
    uint64_t jointTopologyInputBufferBytes;
    wgpu::Buffer jointTopologyOutputBuffer;
    uint64_t jointTopologyOutputBufferBytes;
    wgpu::Buffer jointTopologyReadbackBuffer;
    uint64_t jointTopologyReadbackBufferBytes;
    wgpu::Buffer jointTopologyParamsBuffer;
    wgpu::BindGroupLayout jointTopologyBindGroupLayout;
    wgpu::ComputePipeline jointTopologyPipeline;
    wgpu::Buffer jointColorBuffer;
    uint64_t jointColorBufferBytes;
    wgpu::Buffer jointColorCounterBuffer;
    uint64_t jointColorCounterBufferBytes;
    wgpu::Buffer jointResidualInputBuffer;
    uint64_t jointResidualInputBufferBytes;
    wgpu::Buffer jointResidualBodyBuffer;
    uint64_t jointResidualBodyBufferBytes;
    wgpu::Buffer jointResidualOutputBuffer;
    uint64_t jointResidualOutputBufferBytes;
    wgpu::Buffer jointProposalOutputBuffer;
    uint64_t jointProposalOutputBufferBytes;
    wgpu::Buffer jointProposalResidualBuffer;
    uint64_t jointProposalResidualBufferBytes;
    wgpu::Buffer jointProposalFinalReadbackBuffer;
    uint64_t jointProposalFinalReadbackBufferBytes;
    wgpu::Buffer jointProposalFinalAsyncReadbackBuffer;
    uint64_t jointProposalFinalAsyncReadbackBufferBytes;
    wgpu::BindGroupLayout jointColorBindGroupLayout;
    wgpu::ComputePipeline jointColorPipeline;
    wgpu::BindGroupLayout jointProposalBindGroupLayout;
    wgpu::ComputePipeline jointProposalPipeline;
    wgpu::BindGroupLayout jointProposalApplyBindGroupLayout;
    wgpu::ComputePipeline jointProposalApplyPipeline;
    wgpu::BindGroupLayout jointProposalResidualBindGroupLayout;
    wgpu::ComputePipeline jointProposalResidualPipeline;
    wgpu::BindGroupLayout jointContactSeedBindGroupLayout;
    wgpu::ComputePipeline jointContactSeedPipeline;
    wgpu::Buffer sphereContactBodyBuffer;
    uint64_t sphereContactBodyBufferBytes;
    wgpu::Buffer sphereContactPairBuffer;
    uint64_t sphereContactPairBufferBytes;
    wgpu::Buffer sphereContactCountersBuffer;
    uint64_t sphereContactCountersBufferBytes;
    wgpu::Buffer sphereContactCounterReadbackBuffer;
    uint64_t sphereContactCounterReadbackBufferBytes;
    wgpu::Buffer sphereContactOutputBuffer;
    uint64_t sphereContactOutputBufferBytes;
    wgpu::Buffer sphereContactReadbackBuffer;
    uint64_t sphereContactReadbackBufferBytes;
    wgpu::Buffer sphereContactBodyCountBuffer;
    uint64_t sphereContactBodyCountBufferBytes;
    wgpu::Buffer sphereContactBodyCountReadbackBuffer;
    uint64_t sphereContactBodyCountReadbackBufferBytes;
    wgpu::Buffer sphereContactAdjacencyBuffer;
    uint64_t sphereContactAdjacencyBufferBytes;
    wgpu::Buffer sphereContactGatherOutputBuffer;
    uint64_t sphereContactGatherOutputBufferBytes;
    wgpu::Buffer sphereContactGatherReadbackBuffer;
    uint64_t sphereContactGatherReadbackBufferBytes;
    wgpu::Buffer sphereContactProposalOutputBuffer;
    uint64_t sphereContactProposalOutputBufferBytes;
    wgpu::Buffer sphereContactProposalOutputReadbackBuffer;
    uint64_t sphereContactProposalOutputReadbackBufferBytes;
    wgpu::Buffer sphereContactIterationOutputBuffer;
    uint64_t sphereContactIterationOutputBufferBytes;
    wgpu::Buffer sphereContactIterationScratchBuffer;
    uint64_t sphereContactIterationScratchBufferBytes;
    wgpu::Buffer sphereContactFinalPositionBuffer;
    uint64_t sphereContactFinalPositionBufferBytes;
    wgpu::Buffer sphereContactFinalPositionAsyncReadbackBuffer;
    uint64_t sphereContactFinalPositionAsyncReadbackBufferBytes;
    wgpu::Buffer sphereContactProposalResidualBuffer;
    uint64_t sphereContactProposalResidualBufferBytes;
    wgpu::Buffer sphereContactProposalResidualReadbackBuffer;
    uint64_t sphereContactProposalResidualReadbackBufferBytes;
    wgpu::Buffer sphereContactParamsBuffer;
    wgpu::BindGroupLayout sphereContactBindGroupLayout;
    wgpu::ComputePipeline sphereContactPipeline;
    wgpu::Buffer sphereContactAdjacencyParamsBuffer;
    wgpu::BindGroupLayout sphereContactAdjacencyBindGroupLayout;
    wgpu::ComputePipeline sphereContactAdjacencyPipeline;
    wgpu::BindGroupLayout sphereContactGatherBindGroupLayout;
    wgpu::ComputePipeline sphereContactGatherPipeline;
    wgpu::BindGroupLayout sphereContactProposalBindGroupLayout;
    wgpu::ComputePipeline sphereContactProposalPipeline;
    wgpu::BindGroupLayout sphereContactProposalResidualBindGroupLayout;
    wgpu::ComputePipeline sphereContactProposalResidualPipeline;
    wgpu::BindGroupLayout sphereContactIterationBindGroupLayout;
    wgpu::ComputePipeline sphereContactIterationPipeline;
    wgpu::Buffer sphereGroundParamsBuffer;
    wgpu::BindGroupLayout sphereGroundBindGroupLayout;
    wgpu::ComputePipeline sphereGroundPipeline;
    wgpu::Buffer sapDirectContactCountersBuffer;
    uint64_t sapDirectContactCountersBufferBytes;
    wgpu::Buffer sapDirectContactCountersReadbackBuffer;
    uint64_t sapDirectContactCountersReadbackBufferBytes;
    wgpu::Buffer sapParamsBuffer;
    wgpu::Buffer sapPairParamsBuffer;
    wgpu::Buffer sapSortPassParamsBuffer;
    uint64_t sapSortPassParamsBufferBytes;
    wgpu::BindGroupLayout sapSortBindGroupLayout;
    wgpu::ComputePipeline sapSortPipeline;
    wgpu::BindGroupLayout sapPairBindGroupLayout;
    wgpu::ComputePipeline sapPairPipeline;
    wgpu::BindGroupLayout sapPairOutputBindGroupLayout;
    wgpu::ComputePipeline sapPairOutputPipeline;
    wgpu::BindGroupLayout sapDirectSphereBindGroupLayout;
    wgpu::ComputePipeline sapDirectSpherePipeline;
    wgpu::Buffer sapDirectBoxPairParamsBuffer;
    wgpu::BindGroupLayout sapDirectBoxPairBindGroupLayout;
    wgpu::ComputePipeline sapDirectBoxPairPipeline;
    wgpu::BindGroupLayout bodyPreviewComputeBindGroupLayout;
    wgpu::ComputePipeline bodyPreviewComputePipeline;
    wgpu::BindGroupLayout bodyPreviewBindGroupLayout;
    wgpu::RenderPipeline bodyPreviewGridPipeline;
    wgpu::RenderPipeline bodyPreviewPipeline;
    wgpu::TextureFormat bodyPreviewFormat;
    bool bodyPreviewSurfaceConfigured;
    int bodyPreviewWidth;
    int bodyPreviewHeight;
#endif
};

struct WebGpuPhysicsOptions
{
    bool useSphereContacts;
    bool useGroundContactFeed;
    bool applyContactPositions;
    bool applyGroundContacts;
    bool useResidentGroundContacts;
    bool useCpuFallbackPairs;
    bool useDirectSpherePositionSolve;
    bool skipSapCounterReadback;
    bool validateResidentContacts;
    bool contactSolveDiagnostic;
    bool useJointProposals;
    bool replaceCpuJointSolverWork;
    bool directJointSolveOnly;
    bool directContactSolveOnly;
    bool useResidentPrimitiveContacts;
    bool disableResidentContactReadbacks;
    bool useResidentCounterlessContacts;
    bool asyncFinalPositionReadback;
    bool deferFinalPositionReadback;
    int residentContactIterations;
    float residentContactRelaxation;
    float residentContactMaxUpwardVelocity;
    float residentContactMaxLinearVelocity;
    int jointProposalIterations;

    WebGpuPhysicsOptions();
};

struct WebGpuPhysicsBackend : PhysicsBackend
{
    WebGpuContext *context;
    WebGpuPhysicsOptions options;

    explicit WebGpuPhysicsBackend(WebGpuContext *context = 0, WebGpuPhysicsOptions options = WebGpuPhysicsOptions());
    const char *name() const override;
    void step(Solver &solver) override;
};

struct WebGpuRenderBackend : RenderBackend
{
    const char *name() const override;
    bool available() const;
};
